# Generated by Django 4.2.5 on 2023-11-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_carts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='status',
            field=models.CharField(choices=[('incart', 'incart'), ('orderplaced', 'orderplaced'), ('cancelled', 'cancelled')], default='incart', max_length=15),
        ),
    ]
