# Generated by Django 4.2.5 on 2023-11-09 06:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_book_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0003_alter_carts_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expected_delivery_date', models.DateField(default=datetime.timedelta(days=5))),
                ('status', models.CharField(choices=[('orderplaced', 'orderplaced'), ('dispatched', 'dispatched'), ('in_transit', 'in_transit'), ('delivered', 'delivered'), ('order_cancelled', 'order_cancelled')], default='orderplaced', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
