# Generated by Django 4.2.5 on 2023-11-16 12:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_book_image'),
        ('customer', '0007_alter_order_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 21, 18, 12, 12, 635142), null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='owner.book'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(choices=[('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5')], default='2', max_length=10),
        ),
    ]
